#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${TRADINGCAT_ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
ENV_FILE="$ROOT_DIR/.env"
MODE="${1:-simulate}"
HOST="${2:-127.0.0.1}"
PORT="${3:-11111}"

if [[ -f "$ENV_FILE" ]]; then
  echo ".env already exists at $ENV_FILE"
  echo "Remove it first if you want to regenerate it."
  exit 1
fi

case "$MODE" in
  simulate|SIMULATE)
    FUTU_ENABLED=true
    FUTU_ENVIRONMENT=SIMULATE
    ;;
  real|REAL)
    FUTU_ENABLED=true
    FUTU_ENVIRONMENT=REAL
    ;;
  disabled|off|OFF|false|FALSE)
    FUTU_ENABLED=false
    FUTU_ENVIRONMENT=SIMULATE
    ;;
  *)
    echo "Unsupported mode: $MODE"
    echo "Use one of: simulate, real, disabled"
    exit 1
    ;;
esac

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap_env.sh
TRADINGCAT_PORTFOLIO_VALUE=1000000
TRADINGCAT_BASE_CURRENCY=CNY
TRADINGCAT_DATA_DIR=data
TRADINGCAT_RELOAD=false
TRADINGCAT_POSTGRES_ENABLED=false
TRADINGCAT_POSTGRES_DSN=postgresql:///tradingcat
TRADINGCAT_DUCKDB_ENABLED=false
TRADINGCAT_DUCKDB_PATH=data/research.duckdb
TRADINGCAT_PARQUET_DIR=data/parquet
TRADINGCAT_SCHEDULER_BACKEND=apscheduler
TRADINGCAT_SCHEDULER_AUTOSTART=true
TRADINGCAT_FUTU_ENABLED=$FUTU_ENABLED
TRADINGCAT_FUTU_HOST=$HOST
TRADINGCAT_FUTU_PORT=$PORT
TRADINGCAT_FUTU_ENVIRONMENT=$FUTU_ENVIRONMENT
TRADINGCAT_FUTU_HK_TRADE_MARKET=HK
TRADINGCAT_FUTU_US_TRADE_MARKET=US
TRADINGCAT_FUTU_UNLOCK_TRADE_PASSWORD=
TRADINGCAT_YFINANCE_ENABLED=true
EOF

echo "Created $ENV_FILE"
echo "mode=$MODE host=$HOST port=$PORT"
if [[ "$FUTU_ENVIRONMENT" == "REAL" ]]; then
  echo "Remember to set TRADINGCAT_FUTU_UNLOCK_TRADE_PASSWORD before live trade operations."
fi
